<?php

use Drupal\views\ViewExecutable;

/**
* Implements hook_views_pre_render().
*/
function digitalia_muni_a3d_javascript_views_pre_render(ViewExecutable $view) {
  if (isset($view) && $view->getDisplay()->getPlugin('query')->query()->hasTag('digitalia_calculate_paged')) {
    $view->element['#attached']['library'][] = 'digitalia_muni_a3d_javascript/calculate_position_grid';
    $view->element['#attached']['drupalSettings']['digitaliaMuniA3dJavascript']['calculatePosition'] = [
          'items_per_page' => $view->getItemsPerPage(),
          'display_format' => $view->getDisplay()->getOption('style')['type'],
    ];
  }

  if (isset($view) && $view->getDisplay()->getPlugin('query')->query()->hasTag('digitalia_model_view')) {
    $view->element['#attached']['library'][] = 'digitalia_muni_a3d_javascript/model_view';
  }
}

?>
